name: Vercel React - Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
on:
  push:
    branches-ignore:
      - master
    paths:
      - 'app/**'
      - '!app/backend/**'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: echo "DEPLOY_URL=$(vercel deploy --prebuilt --archive=tgz --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_ENV
      - name: Send Deployment Notification to Discord
        if: ${{ env.DEPLOY_URL != '' }}
        run: |
          DEPLOYMENT_URL=${{ env.DEPLOY_URL }}
          COMMIT_HASH=${{ github.sha }}
          COMMIT_HASH_SHORT=$(git rev-parse --short HEAD)
          COMMIT_USER=${{ github.actor }}
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          BRANCH_NAME=${{ github.ref_name }}
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"## 🚀 Deployed React!\n\n🔗 **Preview Link**: $DEPLOYMENT_URL\n\n📜 *Commit*: [$COMMIT_HASH_SHORT](https://github.com/${{ github.repository }}/commit/$COMMIT_HASH)\n📝 $COMMIT_USER - $COMMIT_MESSAGE\n🌿 Branch: $BRANCH_NAME\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
